### ISSUE TITLE
Add support for parsing report_cdc report from Vivado

### ISSUE THREAD

**Issue by LukasVik** [tsfpga/tsfpga#7]
I would like to support a check somewhere in the build flow for critical CDC warnings. In a perfect world the `report_cdc -details -severity critical output` would be none. However since many designs use IP cores, which are littered with critical CDC warnings, that is not realistic. Instead we probably should have some mechanism with a list of allowed warnings, and any warnings that appear apart from those result in a build error. Also an allowed warning that does not appear should result in a warning printout.

Note that specifically the `CDC-10: Combinational logic detected before a synchronizer warning` is very dangerous. However in a well-made design we should really not have any critical CDC warnings at all.

**Comment by ru551n** [comment]
As far as I know it is possible to promote all messages to errors via a .tcl hook on creation.
Then you can have a another hook between the required implementation steps that fails if there are any errors.

That's at least how we have done it here locally.

**Comment by LukasVik** [comment]
@ru551n Yes, since creating this issue this is the solution that I have pivoted towards also. I think I will close/reject this issue.

The inspiration for this issue comes from a place where I worked where they had a Python tool that parsed all the build logs and some reports. In this system, every single message (info/warning/critical warning/error) had to be white-listed (possibly with wildcard to ignore certain message IDs fully).  I thought this worked quite well. It made it so that if any new messages arrived, they had to be manually inspected, and a choice had to be made whether it was acceptable or not.

But the reason for all of this hassle is that Vivado produces sooo many messages, and the default severity is not always reasonable. So I think manually raising the severity of messages we find unacceptable is a better strategy. That might not be perfect, sometimes there might be a "warning" message in the log that indicates a critical bug. But I think this strategy takes us 90% of the way without too much pain.

**Comment by LukasVik** [comment]
BTW I like the nickname @ru551n, it sounds like a rad Counter Strike nick from the early 2000's.

My nickname was "Sn!per", but I don't dare to use that anymore out of embarrassment.

**Comment by codecache-fpga** [comment]
> BTW I like the nickname @ru551n, it sounds like a rad Counter Strike nick from the early 2000's.
> 
> My nickname was "Sn!per", but I don't dare to use that anymore out of embarrassment.

It kind of is, I am just too lazy to change it to something new that I like. 😉

**Comment by codecache-fpga** [comment]
> @ru551n Yes, since creating this issue this is the solution that I have pivoted towards also. I think I will close/reject this issue.
> 
> The inspiration for this issue comes from a place where I worked where they had a Python tool that parsed all the build logs and some reports. In this system, every single message (info/warning/critical warning/error) had to be white-listed (possibly with wildcard to ignore certain message IDs fully). I thought this worked quite well. It made it so that if any new messages arrived, they had to be manually inspected, and a choice had to be made whether it was acceptable or not.
> 
> But the reason for all of this hassle is that Vivado produces sooo many messages, and the default severity is not always reasonable. So I think manually raising the severity of messages we find unacceptable is a better strategy. That might not be perfect, sometimes there might be a "warning" message in the log that indicates a critical bug. But I think this strategy takes us 90% of the way without too much pain.

Agree. We have list of non-acceptable warnings, mostly related to constraints. If we change some portname or some constraint, the last thing we want is for Vivado to just silently pass timing with not-so-trustworthy timing results.

We allow lots of warnings though, but it is, as you say, quite unmanageable to demote all the warnings from Vivado. With every new release there is something new, and with each new IP you add there are plenty of warnings as well.

It however falls upon the user to periodically inspect the warnings so that something essential does not slip through.

**Comment by ru551n** [comment]
> @ru551n Yes, since creating this issue this is the solution that I have pivoted towards also. I think I will close/reject this issue.
> 
> The inspiration for this issue comes from a place where I worked where they had a Python tool that parsed all the build logs and some reports. In this system, every single message (info/warning/critical warning/error) had to be white-listed (possibly with wildcard to ignore certain message IDs fully). I thought this worked quite well. It made it so that if any new messages arrived, they had to be manually inspected, and a choice had to be made whether it was acceptable or not.
> 
> But the reason for all of this hassle is that Vivado produces sooo many messages, and the default severity is not always reasonable. So I think manually raising the severity of messages we find unacceptable is a better strategy. That might not be perfect, sometimes there might be a "warning" message in the log that indicates a critical bug. But I think this strategy takes us 90% of the way without too much pain.

Agree. We have list of non-acceptable warnings, mostly related to constraints. If we change some portname or some constraint, the last thing we want is for Vivado to just silently pass timing with not-so-trustworthy timing results.

We allow lots of warnings though, but it is, as you say, quite unmanageable to demote all the warnings from Vivado. With every new release there is something new, and with each new IP you add there are plenty of warnings as well.

It however falls upon the user to periodically inspect the warnings so that something essential does not slip through.

**Comment by ru551n** [comment]
> It kind of is, I am just too lazy to change it to something new that I like. 😉
> 
> Never be ashamed of where we came from! 😋

It kind of is, I am just too lazy to change it to something new that I like. 😉

Never be ashamed of where we came from! 😋
