### ISSUE TITLE
Add `super().__init__()` to `BaseModule`'s `__init__` to simplify multiple inheritance in modules

### ISSUE THREAD

**Issue by ru551n** [tsfpga/tsfpga#84]
We have implemented a child class with the `BaseModule`  as parent, let's call it `BaseModuleLocal` . Also we have implemented a mixin class `FuncMixin` with which we selectively inject functionality into our modules.
So our module looks like this:

```python
class Module(BaseModuleLocal, FuncMixin):
    def __init__(self, *args):
        super().__init__(args)
``` 

The problem here is that (as far as I understand, I may be wrong) is that python calls to `super().__init__()` calls the **next** class' `__init__` in the MRO.

So that when doing init, we go from `BaseModuleLocal` -> `BaseModule`, and then it stops, since `BaseModule` has no call to `super().__init__()`.
The workaround is to have the `FuncMixin` first instead:

```python
class Module(FuncMixin, BaseModuleLocal):
    def __init__(self, *args):
        super().__init__(args)
```
And in the `FuncMixin` we ensure that it calls `super().__init__()` last in it's `__init__`.

So we go from `FuncMixin` -> `BaseModuleLocal` -> `BaseModule`, and we have the complete "chain" covered.

It is workable, but it assumes that everyone knows that we need to put the mixins first, which might not be obvious for our users. 

However the following will fail, since `BaseModule` will break the chain.

```python
class Module(FuncMixinA, BaseModuleLocal, FuncMixinB):
    def __init__(self, *args):
        super().__init__(args)
```

So my suggestion is to put a call to `super().__init__()` at the end of `BaseModule`'s `__init__`.
This assumes that we don't pass any arguments to the mixins (we shouldn't do that anyway). If we want to allow multiple inheritance, we should only need to pass `**kwargs` IIRC.

You probably know Python's inner workings better than I do, so feel free to suggest a better solution in alignment with TSFPGA's vision. 😉

**Comment by LukasVik** [comment]
Cool! I'm busy for a few days, but I will look into this towards the end of the week!
