### ISSUE TITLE
Latest VUnit master breaks netlist builds

### ISSUE THREAD

**Issue by ru551n** [tsfpga/tsfpga#87]
**Description**
Due to changes in VUnit internals, netlist builds are broken as of https://github.com/VUnit/vunit/pull/1025, which likely will be included in VUnit v4.8.0.

```
Traceback (most recent call last):
  File "/root/git/vunit-vc/build.py", line 38, in <module>
    main()
  File "/root/git/vunit-vc/build.py", line 29, in main
    setup_and_run(
  File "/root/git/vunit-vc/tsfpga/tsfpga/examples/build_fpga_utils.py", line 218, in setup_and_run
    build_ok = projects.build(
  File "/root/git/vunit-vc/tsfpga/tsfpga/build_project_list.py", line 218, in build
    return self._run_build_wrappers(
  File "/root/git/vunit-vc/tsfpga/tsfpga/build_project_list.py", line 311, in _run_build_wrappers
    report.print_str()
  File "/root/git/vunit-vc/vunit/vunit/test/report.py", line 164, in print_str
    test_result.print_status(self._printer, padding=max_len, max_time=max_time)
TypeError: BuildResult.print_status() got an unexpected keyword argument 'max_time'
``` 

The fix seems easy enough though, maybe add `**kwargs` or add specific `max_time` argument.
Not required until VUnit v.4.8.0 is released though.

**Comment by LukasVik** [comment]
For future reference: 

https://github.com/VUnit/vunit/pull/1025 is not included in the latest VUnit release as of this date, which is 4.7.0.  It is however merged to the VUnit master branch, so it will be included in VUnit > 4.7.0.

To solve the situation I have:

1. Made a tsfpga release from main with VUnit pegged to <= 4.7.0.
2. Updated current tsfpga main to handle the API on VUnit master.
3. Pegged VUnit to > 4.7.0 (**which is currently not released**) on tsfpga main.

Bullet 3 means that we can not make a new tsfpga release before VUnit makes their next release.

**Comment by LukasVik** [comment]
Fixed on main now!

**Comment by LukasVik** [comment]
I temporarily reverted the fix in order to make an emergency PyPI release. The fix is back on main now, so that our main works with lates VUnit master.
